#!/bin/sh

# get current python version
PYTHON_VERSION="$(which python)"
#call cli with arguments
clear
$PYTHON_VERSION -m r3con1z3r.main "$@" || python -m r3con1z3r.main "$@" || python2 -m r3con1z3r.main "$@" || python3 -m r3cno1z3r.main "$@"
